name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.6.0
  - ipython=8.12.2
  - notebook=7.0.2
  - jupyterlab=4.0.5
  - cookiecutter=2.3.0
  - hydra-core=1.3.2
  - matplotlib=3.7.2
  - pandas=2.0.3
  - pip=23.2.1
  - pip:
      - wandb==0.15.8
