name: genre_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip==23.2.1
  - mlflow==2.5.0
  - hydra-core=1.3.2
  - pip:
      - wandb==0.15.8
      - hydra-joblib-launcher==1.2.0
