name: evaluate_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==2.0.3
  - pip==23.2.1
  - scikit-learn=0.24.1
  - matplotlib==3.7.2
  - plotly==4.4.1
  - pillow=8.1.2
  - mlflow==2.5.0
  - pip:
    - wandb==0.15.8
