main:
  cat_features: [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
  ]
  num_features: ["age", "fnlwgt", "education-num", "capital-gain", "capital-loss", "hours-per-week"]
  label: "salary"
  model_path: "model/lr_model.pkl"
  slice_output_path: "slice_output.txt"
  data_path: "data/census_clean.csv"
  test_size: 0.2
